behaviors:
  CharacterBehav:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 512
      buffer_size: 5120
      learning_rate: 3.0e-5
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 256
      num_layers: 3

    # Trainer configurations common to all trainers
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 5000
    keep_checkpoints: 50
    checkpoint_interval: 5000
    threaded: false
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99