behaviors:
  CharacterBehav:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 128
      buffer_size: 1280
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2

    # Trainer configurations common to all trainers
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 50000
    keep_checkpoints: 50
    checkpoint_interval: 50000
    threaded: false
    init_path: null

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 0.1
        gamma: 0.99
      gail:
        strength: 0.8
        gamma: 0.99
        demo_path: Demos
    behavioral_cloning:
        strength: 1
        gamma: 0.99
        demo_path: Demos